DELETE FROM public.products;

INSERT INTO public.products (id, name, origin, price, category) VALUES
  ('kaju', 'Kaju', 'Whole Cashews W-180 · Mangalore Coast', 880, 'dry-fruits'),
  ('badam', 'Badam', 'Mamra Almonds · Kashmir Valley', 780, 'dry-fruits'),
  ('kishmish', 'Kishmish', 'Golden Raisins · Nashik', 420, 'dry-fruits'),
  ('akrot', 'Akrot', 'Walnut Kernels · Kashmir', 640, 'dry-fruits'),
  ('pista', 'Pista', 'Roasted & Salted · Kerman', 1140, 'dry-fruits'),
  ('medjoul-dates', 'Medjoul Dates', 'Jumbo Grade · Jordan Valley', 920, 'dry-fruits'),
  ('breakfast-khatta-meetha', 'Breakfast Khatta Meetha', 'Berries, seeds & cashews', 690, 'flavoured'),
  ('mix-vegetable-masala', 'Mixed Vegetable Masala', 'Savoury spiced medley', 540, 'flavoured'),
  ('kaju-thai-puff', 'Kaju Thai Puff', 'Sweet-chilli crunch coating', 720, 'flavoured'),
  ('trail-mix', 'Trail Mix', 'Seeds, berries & raisins', 610, 'flavoured'),
  ('peri-peri-kaju', 'Peri Peri Kaju', 'Fiery peri-peri cashews', 760, 'flavoured'),
  ('panchrattan', 'Panchrattan', 'Masala-roasted dry fruit mix', 700, 'flavoured'),
  ('paan-kishmish', 'Paan Kishmish', 'Betel-leaf glazed raisins', 520, 'flavoured'),
  ('blueberry-almond', 'Blueberry Almond', 'Fruit-dusted almonds', 840, 'flavoured'),
  ('paan-shots', 'Paan Shots', 'Paan-filled chocolate pearls', 580, 'flavoured'),
  ('paan-dates', 'Paan Dates', 'Dates stuffed with paan', 880, 'flavoured'),
  ('choco-dip-almonds', 'Chocodip Almonds', 'Dark chocolate coated badam', 820, 'flavoured'),
  ('roseate-grace', 'Roseate Grace', '250g Almonds · 250g Cashews', 2030, 'hampers-luxury'),
  ('amethyst-elegance', 'Amethyst Elegance', '250g Almonds · 250g Raisins · 250g Breakfast Khatta Meetha', 2525, 'hampers-luxury'),
  ('the-silver-empress', 'The Silver Empress', '500g Breakfast Khatta Meetha · 200g Almonds', 2750, 'hampers-luxury'),
  ('the-floral-jewel', 'The Floral Jewel', '500g Almonds', 2030, 'hampers-luxury'),
  ('the-oval-ruby', 'The Oval Ruby', '9 Chocolates · 250g Trail Mix · 250g Almonds', 2075, 'hampers-luxury'),
  ('sapphire-chest', 'Sapphire Chest', '9 Chocolates · 200g Almonds · 250g Raisins', 2435, 'hampers-luxury'),
  ('gajraj-royale', 'Gajraj Royale', '500g Almonds', 3200, 'hampers-luxury'),
  ('emerald-grace', 'Emerald Grace', '250g Almonds · 250g Kishmish · 250g Trail Mix', 2300, 'hampers-luxury'),
  ('the-blush-royale', 'The Blush Royale', '9 Chocolates · 200g Chocolate · 200g Almonds · 200g Raisins · 250g Breakfast Khatta Meetha', 2660, 'hampers-luxury'),
  ('the-gilded-bird', 'The Gilded Bird', '500g Almonds', 2435, 'hampers-luxury'),
  ('shagun-e-noor', 'Shagun-E-Noor', '250g Almonds · 250g Breakfast Khatta Meetha', 3300, 'hampers-luxury'),
  ('luxe-royale', 'Luxe Royale', '500g Breakfast Khatta Meetha', 1950, 'hampers-luxury'),
  ('maroon-majesty', 'Maroon Majesty', '250 gm Almonds · 250 gm Breakfast Khatta Meetha · 9 Paan Dates', 2750, 'hampers-luxury'),
  ('the-peach-affair', 'The Peach Affair', '250 gms Almonds · 250 gms Cashews', 3175, 'hampers-luxury'),
  ('olive-garden', 'Olive Garden', '250 gms Almonds · 250 gms Cashews', 3175, 'hampers-luxury'),
  ('lavender-opulence', 'Lavender Opulence', '9 Piece Chocolates · 250 gms Almonds · 250 gms Cashews', 3075, 'hampers-luxury'),
  ('the-silver-heirloom', 'The Silver Heirloom', '250 gms Almonds · 350 gms Trail mix', 3200, 'hampers-luxury'),
  ('the-royal-dynasty', 'The Royal Dynasty', '250 gms Breakfast Khatta Meetha · 250 gm Raisins · 250 gm Barari Chocolate Dates', 3750, 'hampers-luxury'),
  ('circle-of-abundance', 'Circle of Abundance', '200 gms Almonds · 200 gms Raisins · 200 gms Cashews · 200 gms Pistachios', 2400, 'hampers-luxury'),
  ('the-pearl-garden', 'The Pearl Garden', '9 pieces Chocolates · 200 gms Breakfast Khatta Meetha', 2400, 'hampers-luxury'),
  ('the-silver-majestic', 'The Silver Majestic', '250 gms Raisins · 250 gms Almonds · 250 gms Cashews', 3200, 'hampers-luxury'),
  ('moonstone-charm', 'Moonstone Charm', '1/2 kg Breakfast Khatta Meetha', 1950, 'hampers-luxury'),
  ('lilac-grace', 'Lilac Grace', '200 gms Almonds · 200 gms Trail mix', 2400, 'hampers-luxury'),
  ('ivory-bloom', 'Ivory Bloom', '200g Almonds · 200g Trail Mix', 1000, 'hampers-corporate'),
  ('noor-mahal', 'Noor Mahal', '250g Almonds · 250g Raisins', 975, 'hampers-corporate'),
  ('the-lotus-legacy', 'The Lotus Legacy', '200g Almonds · 200g Breakfast Khatta Meetha', 1000, 'hampers-corporate'),
  ('mint-mahal', 'Mint Mahal', '200g Almonds · 200g Breakfast Khatta Meetha · 9 Paan Dates', 1500, 'hampers-corporate'),
  ('the-royal-heritage', 'The Royal Heritage', '200g Almonds · 200g Breakfast Khatta Meetha · 9 Paan Dates', 1575, 'hampers-corporate'),
  ('the-regal-trio', 'The Regal Trio', '200g Almonds · 200g Cashews · 200g Raisins', 1575, 'hampers-corporate'),
  ('the-blue-dynasty', 'The Blue Dynasty', '200g Almonds · 200g Cashews · 200g Raisins · 200g Trail Mixture', 1725, 'hampers-corporate'),
  ('the-peacock-blush', 'The Peacock Blush', '½ kg Trail Mixture', 2100, 'hampers-corporate'),
  ('navy-dynasty', 'Navy Dynasty', '250g Almonds · 250g Cashews · 250g Raisins', 1575, 'hampers-corporate'),
  ('the-midnight-basket', 'The Midnight Basket', '250g Almonds · 250g Raisins · 250g Cashews', 2340, 'hampers-corporate'),
  ('shehnai-silver-casket', 'Shehnai Silver Trousseau Casket', 'Pure Silver Filigree Box · Saffron, Mamra & Medjool Dates', 4250, 'hampers-wedding'),
  ('maharaja-vivah-hamper', 'Maharaja Vivah Keepsake Hamper', 'Velvet Embroidered Chest · 4 Jars Heritage Nuts & Mithai', 4850, 'hampers-wedding'),
  ('gulab-shagun-potli-box', 'Gulab Shagun Potli Box', 'Gilded Floral Casket · Zari Silk Potlis with Mamra & Pistachios', 3650, 'hampers-wedding'),
  ('ananta-wedding-casket', 'Ananta Royal Wedding Casket', 'Handcrafted Lattice Basket · Dry Fruits & Cardamom', 3950, 'hampers-wedding'),
  ('california-almonds', 'California Almonds', 'Premium Grade · California Orchards', 1200, 'almonds'),
  ('cal-almonds-sanora', 'Cal Almonds (Sanora)', 'Sanora Variety · California Orchards', 1800, 'almonds'),
  ('mamra-almonds', 'Mamra Almonds', 'High-Oil Heritage Kernels · Kashmir / Iran', 4200, 'almonds'),
  ('gurbandi-almonds', 'Gurbandi Almonds', 'Chhoti Giri · Rich in Natural Oils', 1500, 'almonds'),
  ('roasted-almonds', 'Roasted Almonds', 'Slow Roasted & Lightly Salted', 1350, 'almonds'),
  ('flavoured-blueberry-almonds', 'Blueberry Almonds', 'Sun-Dried Wild Blueberry Glaze', 1250, 'flavoured-almonds'),
  ('flavoured-chocolate-almonds', 'Chocolate Almonds', 'Artisanal Rich Dark Cocoa Coating', 1250, 'flavoured-almonds'),
  ('flavoured-paan-almonds', 'Paan Almonds', 'Meetha Paan & Rose Petal Glaze', 1250, 'flavoured-almonds'),
  ('flavoured-thai-puff-almonds', 'Thai Puff Almonds', 'Sweet Chilli & Kaffir Crunch', 1250, 'flavoured-almonds'),
  ('flavoured-rainbow-almonds', 'Rainbow Almonds', 'Multi-Fruit Glazed Crisp Almonds', 1250, 'flavoured-almonds'),
  ('flavoured-barbeque-almonds', 'Barbeque Almonds', 'Smoky Paprika & Herbs Infusion', 1250, 'flavoured-almonds'),
  ('flavoured-rose-almonds', 'Rose Almonds', 'Kashmiri Rose Petal Glaze', 1250, 'flavoured-almonds'),
  ('flavoured-pudina-almonds', 'Pudina Almonds', 'Zesty Mint & Tangy Spices', 1250, 'flavoured-almonds'),
  ('flavoured-kulfi-almonds', 'Kulfi Almonds', 'Traditional Desi Kulfi Flavoured', 1250, 'flavoured-almonds'),
  ('flavoured-kali-mirch-almonds', 'Kali Mirch Almonds', 'Fresh Crushed Malabar Black Pepper', 1250, 'flavoured-almonds'),
  ('pista-roasted-salted-shell', 'Pista Roasted & Salted (Shell)', 'Jumbo In-Shell · Iranian Salted', 1900, 'pistachio'),
  ('cashew-w320', 'Cashew Nuts (W 320)', 'Standard Whole Cashews · Mangalore', 1300, 'cashew-nut'),
  ('cashew-w240', 'Cashew Nuts (W 240)', 'Large Whole Kernels · Selected Grade', 1400, 'cashew-nut'),
  ('cashew-w210', 'Cashew Nuts (W 210)', 'Jumbo Whole Cashews · Superior Grade', 1600, 'cashew-nut'),
  ('cashew-w180', 'Cashew Nuts (W 180)', 'King Sized Cashews · Highest Grade', 1800, 'cashew-nut'),
  ('cashew-2-tukda', 'Cashew (2 Tukda)', 'Split Halves · Clean & Sorted', 1050, 'cashew-nut'),
  ('cashew-4-tukda', 'Cashew (4 Tukda)', 'Quarter Pieces · Culinary & Snacking', 950, 'cashew-nut'),
  ('cashew-roasted-salted', 'Roasted Salted Cashew', 'Slow Toasted with Sea Salt', 1350, 'cashew-nut'),
  ('cashew-peri-peri', 'Peri Peri Cashew', 'Zesty Bird''s Eye Chilli Seasoning', 1300, 'cashew-nut'),
  ('cashew-nut-cracker', 'Cashew Nut Cracker', 'Spiced Crisp Coated Cashews', 1300, 'cashew-nut'),
  ('cashew-breakfast-khatta-meetha', 'Breakfast Khatta Meetha', 'Sweet & Tangy Medley with Cashews', 1100, 'cashew-nut'),
  ('cashew-panchratna-mixture', 'Panchratna Mixture', 'Masala Roasted 5-Gem Luxury Blend', 1400, 'cashew-nut'),
  ('cashew-kaju-thai-puff', 'Kaju Thai Puff', 'Thai Sweet Chilli Glaze & Crispy Crunch', 1300, 'cashew-nut'),
  ('cashew-masala', 'Cashew Masala', 'Rich Chaat Masala & Roasted Kernels', 1350, 'cashew-nut'),
  ('cashew-pudina', 'Cashew Pudina', 'Refreshing Mint & Coriander Crust', 1350, 'cashew-nut'),
  ('cashew-kali-mirch', 'Cashew Kali Mirch', 'Crushed Black Pepper & Rock Salt', 1350, 'cashew-nut'),
  ('cashew-korean-chilli', 'Cashew Korean Chilli', 'Gochugaru Spiced Savoury Cashews', 1350, 'cashew-nut'),
  ('raisins-plain', 'Raisins Plain', 'Sun-Dried Sweet Green Raisins · Nashik', 850, 'raisins'),
  ('raisins-paan-flavour', 'Raisins Paan Flavour', 'Refreshing Betel & Rose Infused', 900, 'raisins'),
  ('raisins-kala-khatta', 'Raisins Kala-Khatta Flavour', 'Tangy Jamun & Kala Khatta Dusting', 900, 'raisins'),
  ('raisins-black-kali-darak', 'Raisins Black (Kali Darak)', 'Seedless Black Grapes · Antioxidant Rich', 750, 'raisins'),
  ('raisins-rose-malai', 'Rose Malai Kishmish', 'Gulkand & Cream Glazed Raisins', 1000, 'raisins'),
  ('raisins-munakka', 'Munakka', 'Large Seeded Ayurvedic Golden Raisins', 1200, 'raisins'),
  ('raisins-mango-kishmish', 'Mango Kishmish', 'Alphonso Mango Pulped Raisins', 1000, 'raisins'),
  ('walnuts-chille', 'Walnuts (Chille)', 'Extra Light Halves Kernels · Kashmir', 1900, 'walnut'),
  ('walnuts-tukde', 'Walnuts (Tukde)', 'Broken Walnut Pieces · Kashmir', 1500, 'walnut'),
  ('walnuts-shell', 'Walnuts (Shell)', 'Whole In-Shell Kagzi Walnuts', 1200, 'walnut'),
  ('saffron-indian-kesar', 'Indian Saffron (Kesar)', 'Pure Mongra Grade · Pampore, Kashmir', 300, 'saffron'),
  ('saffron-afghani-kesar', 'Afghani Saffron (Kesar)', 'Super Negin Grade · Herat Valley', 350, 'saffron'),
  ('df-blueberry', 'Blueberry', 'Plump Whole Dried Blueberries', 1700, 'dried-fruits'),
  ('df-black-currant', 'Black Current', 'Tart & Sweet Sun-Dried Currants', 900, 'dried-fruits'),
  ('df-cranberry', 'Cranberry', 'Whole Sliced Dried Cranberries', 750, 'dried-fruits'),
  ('df-kiwi-coin', 'Kiwi Coin', 'Dehydrated Kiwi Slices', 650, 'dried-fruits'),
  ('df-mango-slices', 'Mango Slices', 'Sweet Dehydrated Mango Strips', 850, 'dried-fruits'),
  ('df-pineapple-coin', 'Pineapple Coin', 'Naturally Sweet Pineapple Rings', 850, 'dried-fruits'),
  ('df-strawberries', 'Strawberries', 'Whole Sun-Dried Sweet Strawberries', 900, 'dried-fruits'),
  ('df-cherry', 'Cherry', 'Sweet Dried Red Cherries', 800, 'dried-fruits'),
  ('df-fruit-cocktail', 'Fruit Cocktail', 'Medley of Exotic Dehydrated Fruits', 800, 'dried-fruits'),
  ('df-mixed-berries', 'Mixed Berries', 'Cranberry, Blueberry, Strawberry Blend', 1000, 'dried-fruits'),
  ('df-mix-fruit-milk-chocodip', 'Mix Fruit Milk Chocodip', 'Dehydrated Fruits in Creamy Milk Chocolate', 1000, 'dried-fruits'),
  ('df-dried-apricot', 'Dried Apricot', 'Sun-Cured Turkish Khubani', 1200, 'dried-fruits'),
  ('df-prunes', 'Prunes', 'Pitted Californian Sun-Dried Prunes', 1100, 'dried-fruits'),
  ('df-mix-fruit-chatpata', 'Mix Fruit Chatpata', 'Spiced & Tangy Dried Fruit Chunks', 1000, 'dried-fruits'),
  ('exotic-brazil-nuts', 'Brazil Nuts', 'Whole Amazonian Brazil Nuts · Selenium Rich', 3400, 'exotic-nuts'),
  ('exotic-pine-nuts-shell', 'Pine Nuts (Shell)', 'Chilgoza In-Shell · Himalayan Pine', 3600, 'exotic-nuts'),
  ('exotic-pine-nuts-without-shell', 'Pine Nuts (Without Shell)', 'Raw Chilgoza Kernels · Pristine Quality', 6500, 'exotic-nuts'),
  ('exotic-hazelnut', 'Hazelnut', 'Roasted Filbert Kernels · Turkey', 2600, 'exotic-nuts'),
  ('exotic-pecan-nuts', 'Pecan Nuts', 'Buttery American Pecan Halves', 2200, 'exotic-nuts'),
  ('exotic-macadamia-nut', 'Macadamia Nut', 'Rich Creamy Whole Macadamias · Australia', 2900, 'exotic-nuts'),
  ('exotic-pecan-vanilla', 'Pecan Vanilla', 'Vanilla Glazed Crunchy Pecans', 1300, 'exotic-nuts'),
  ('exotic-tiger-nut', 'Tiger Nut', 'Nutritious Sweet Earthy Chufa', 1100, 'exotic-nuts'),
  ('seeds-pumpkin', 'Pumpkin Seeds', 'AAA Grade Green Pepitas', 800, 'seeds'),
  ('seeds-sunflower', 'Sunflower Seeds', 'Raw Shelled Sunflower Kernels', 500, 'seeds'),
  ('seeds-flax', 'Flax Seeds', 'Golden Brown Omega-3 Rich Seeds', 400, 'seeds'),
  ('seeds-chia', 'Chia Seeds', 'Organic Black Chia Seeds', 600, 'seeds'),
  ('seeds-quinoa', 'Quinoa Seeds', 'Whole White Royal Quinoa Grain', 350, 'seeds'),
  ('seeds-watermelon', 'Watermelon Seeds', 'Magaz Kernels · Shelled Watermelon Seeds', 950, 'seeds'),
  ('seeds-melon', 'Melon Seeds', 'Shelled Kharbooza Seeds', 950, 'seeds'),
  ('seeds-mixed-with-berries', 'Mixed Seeds With Berries', '7-Seed & Berry Superfood Power Mix', 800, 'seeds'),
  ('special-cardamom-8mm-bold', 'Cardamom (8mm Bold)', 'Extra Bold Green Elaichi · Idukki, Kerala', 4500, 'special'),
  ('special-silver-cardamom', 'Silver Cardamom', 'Silver Leaf Coated Royal Cardamom', 2700, 'special'),
  ('special-dry-dates', 'Dry Dates', 'Yellow & Brown Chuara', 500, 'special'),
  ('special-anjeer', 'Anjeer', 'Handpicked Large Afghani Figs', 1950, 'special'),
  ('special-mishri-kesar', 'Mishri Kesar', 'Rock Sugar Infused with Pure Saffron', 400, 'special'),
  ('special-khurbani', 'Khurbani', 'Dried Wild Mountain Apricots', 800, 'special'),
  ('special-amla-candy', 'Amla Candy', 'Sweet & Tangy Indian Gooseberry Chunks', 600, 'special'),
  ('special-paan-khajoor-box', 'Paan Khajoor (400gms in Box)', 'Meetha Paan Stuffed Dates Box', 400, 'special'),
  ('special-amla-muraba-1kg', 'Amla Muraba 1kg', 'Traditional Sweet Herbal Preserve', 375, 'special'),
  ('special-paanshots', 'Paanshots', 'Refreshing Paan Chocolate Bombs', 900, 'special'),
  ('special-dates-frad', 'Dates (Frad)', 'Oman Fardh Sweet Dark Dates', 700, 'special'),
  ('special-dates-medjoul', 'Dates (Medjoul)', 'Large Meaty King Medjool Dates', 1400, 'special'),
  ('special-dates-paan', 'Dates (Paan)', 'Stuffed with Gulkand & Paan Masala', 1200, 'special'),
  ('special-dates-dryfruit', 'Dates Dryfruit', 'Pitted Dates Stuffed with Almonds & Cashews', 1200, 'special'),
  ('special-shahi-nut', 'Shahi Nut', 'Royal Saffron Flavoured Nut Blend', 1000, 'special'),
  ('hb-granola-bites', 'Granola Bites', 'Oats, Honey & Dry Fruit Energy Clusters', 900, 'healthy-bites'),
  ('hb-stone-chocolate', 'Stone Chocolate', 'River Stone Shaped Milk Chocolate Candy', 750, 'healthy-bites'),
  ('hb-fruit-nut-muesli', 'Fruit & Nut Muesli', 'Rolled Grains with Fruits & Nuts', 800, 'healthy-bites'),
  ('hb-dry-fruit-laddoo', 'Dry Fruit Laddoo', 'Sugar-Free Pure Ghee Dry Fruit Bites', 1000, 'healthy-bites'),
  ('hb-mixed-vegetable-masala', 'Mixed Vegetable Masala', 'Vacuum-Fried Crispy Spiced Veggies', 1200, 'healthy-bites'),
  ('hb-dried-fruit-masala', 'Dried Fruit Masala', 'Spiced Masala Roasted Fruit & Nut Medley', 1400, 'healthy-bites'),
  ('makhana-plain', 'Makhana Plain', 'Jumbo Fox Nuts (Phool Makhana) · Bihar', 1600, 'makhanas'),
  ('oil-almond-100ml', 'Almond Oil (100ml)', '100% Pure Cold Pressed Roghan Badam Shirin', 1200, 'oil')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  origin = EXCLUDED.origin,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  updated_at = timezone('utc'::text, now());
