// This file is automatically generated. Do not edit it directly.
import "@/lib/server-polyfill";
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please add them to your .env file.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    // Node.js < 22 WebSocket polyfill for @supabase/supabase-js
    // createClient instantiates RealtimeClient which requires WebSocket to exist.
    // Since we don't use realtime on the server, a dummy class prevents the crash.
    if (typeof globalThis.WebSocket === "undefined") {
      globalThis.WebSocket = class WebSocket {} as unknown as typeof WebSocket;
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      accessToken: async () => token,
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // Create a temporary client strictly for auth verification
    // because the primary client has accessToken configured, which explicitly disables .auth.getUser()
    const authClient = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await authClient.auth.getUser(token);
    if (error || !data?.user) {
      console.error("Auth Middleware Error:", error);
      throw new Error("Unauthorized: Invalid token or user not found");
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        user: data.user,
      },
    });
  },
);

export const requireAdminAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const { supabase, userId } = context;

    const { data: profile, error } = await supabase
      .from("profiles")
      .select("is_admin")
      .eq("id", userId)
      .single();

    if (error || !profile || !profile.is_admin) {
      const { logSecurityEvent } = await import("@/lib/logger");
      const { getClientIp } = await import("@/lib/rate-limiter");
      const request = getRequest();
      const ip = getClientIp(request);

      logSecurityEvent("WARN", {
        event: "ADMIN_AUTH_FAILED",
        message: "Unauthorized attempt to access admin-restricted resource",
        userId,
        ip,
        statusCode: 403,
        details: { profileFound: !!profile, isAdmin: !!profile?.is_admin },
        error: error ? error.message : undefined,
      });

      throw new Error("Forbidden: Admin access required");
    }

    return next({
      context: {
        ...context,
        isAdmin: true,
      },
    });
  });
